"""
Django settings for Pricing project.

Generated by 'django-admin startproject' using Django 2.1.12.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'q-tu^__vp$b=$v1ob6zm03xg1n9-ff_h3^1vb34!!#u61qxs)a'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['pricing-demo.logistikgo.com','127.0.0.1','localhost']


# Application definition

FILE_UPLOAD_HANDLERS = ("django_excel.ExcelMemoryFileUploadHandler",
                        "django_excel.TemporaryExcelFileUploadHandler")

INSTALLED_APPS = [
    'django.contrib.humanize',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'debug_toolbar',
    'django_tables2',
    'users',
    'usersadmon',
    'Home',
    'TransportistasProspecto',
    'Expediente',
    'chartjs',
    'Rutas',
    'Costeo',
    'storages',
    'rest_framework',
]

MIDDLEWARE = [
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Pricing.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR + '/templates/'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Pricing.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': "sql_server.pyodbc",
        'NAME': "LogistikGO_Pricing_debug",
        'HOST': "104.210.157.194",
        'USER': "SA",
        'PASSWORD': "El45sC92s7",
        'PORT': "1433",
         'OPTIONS': {
            'driver': "ODBC Driver 17 for SQL Server",
        },
    },
    'users': {
        'ENGINE': "sql_server.pyodbc",
        'NAME': "LogistikGO_Admon_Copiar_01",
        'HOST': "logistikgo.database.windows.net",
        'USER': "QUR3n5qk4F33",
        'PASSWORD': "Hi0p68To45lzXp0klf",
        'PORT': "1433",
        'OPTIONS': {
            'driver': "ODBC Driver 17 for SQL Server",
        },
    }
}

DATABASE_ROUTERS = ['users.router.AuthRouter', ]


AUTHENTICATION_BACKENDS = (
    'users.backends.EmailBackend',
    )

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


INTERNAL_IPS = [
    # ...
    '127.0.0.1',
    # ...
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

DEFAULT_FILE_STORAGE = 'backend.custom_azure.AzureMediaStorage'

STATIC_URL = '/static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

AUTH_USER_MODEL = 'users.User'
LOGIN_REDIRECT_URL = '/Home'
SESSION_COOKIE_AGE = 21600

MEDIA_LOCATION = "archivospricing"
AZURE_ACCOUNT_NAME = "lgklataforma"
AZURE_CUSTOM_DOMAIN = f'{AZURE_ACCOUNT_NAME}.blob.core.windows.net'
MEDIA_URL = f'https://{AZURE_CUSTOM_DOMAIN}/{MEDIA_LOCATION}/'

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = '*****'
EMAIL_HOST_PASSWORD = '****'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
PDFKIT = r'C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe'
RUTAPDF = 'http://localhost:8000/costeo/hojaPdfCosteo/'
ARCHIVOMAESTRO = 'C:\Develop-Pricing\Proyecto-Pricing\Pricing\ArchivoMaestro.xlsx'
EXCELGENERAL = 'C:\Develop-Pricing\Proyecto-Pricing\Pricing\excelGeneral.xlsx'