# Generated by Django 2.1.12 on 2020-06-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDTransportista', models.IntegerField(default=0)),
                ('Fecha', models.DateTimeField()),
                ('RepLGK', models.CharField(blank=True, max_length=254, null=True)),
                ('RepTransportista', models.CharField(blank=True, max_length=254, null=True)),
                ('Active', models.BooleanField(default=1)),
            ],
            options={
                'db_table': 'Bitacora',
            },
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDTransportista', models.IntegerField(default=0)),
                ('FormatoAlta', models.FileField(upload_to='documents/')),
                ('ActaConstitutiva', models.FileField(upload_to='documents/')),
                ('CedulaFiscal', models.FileField(upload_to='documents/')),
                ('IFERepresentante', models.FileField(upload_to='documents/')),
                ('ComprobanteDomicilio', models.FileField(upload_to='documents/')),
                ('CaratulaBancaria', models.FileField(upload_to='documents/')),
                ('ConvenioConfidencialidad', models.FileField(upload_to='documents/')),
                ('ContratoServicios', models.FileField(upload_to='documents/')),
                ('ConvenioTarifas', models.FileField(upload_to='documents/')),
                ('Descripcion', models.FileField(upload_to='documents/')),
                ('Permisos', models.FileField(upload_to='documents/')),
                ('Licencias', models.FileField(upload_to='documents/')),
                ('Active', models.BooleanField(default=1)),
            ],
            options={
                'db_table': 'Expediente',
            },
        ),
        migrations.CreateModel(
            name='Extras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDTransportista', models.IntegerField(default=0)),
                ('Image', models.FileField(upload_to='documents/')),
                ('Stars', models.IntegerField(default=0)),
                ('TarjetaDirector', models.FileField(upload_to='documents/')),
                ('TarjetaVentas', models.FileField(upload_to='documents/')),
                ('Active', models.BooleanField(default=1)),
            ],
            options={
                'db_table': 'Extras',
            },
        ),
    ]
