# Generated by Django 2.1.12 on 2020-06-24 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransportistasProspecto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactos',
            name='CorreoAdicional',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contactos',
            name='Profesion',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contactos',
            name='Puesto',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contactos',
            name='SegundoNombre',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='transportistasprospectos',
            name='Credito',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transportistasprospectos',
            name='NumeroExt',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='transportistasprospectos',
            name='NumeroInt',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='transportistasprospectos',
            name='PolizaSeguro',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='transportistasprospectos',
            name='Seguridad',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
