# Generated by Django 2.1.12 on 2020-06-23 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Rutas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Costeo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CPOrigen', models.CharField(max_length=254)),
                ('CPDestino', models.CharField(max_length=254)),
                ('Empresa', models.CharField(max_length=254)),
                ('Casetas', models.DecimalField(decimal_places=2, max_digits=30)),
                ('Kilometros', models.DecimalField(decimal_places=2, max_digits=30)),
                ('Producto', models.CharField(max_length=254)),
                ('TotalCostos', models.DecimalField(decimal_places=2, max_digits=30)),
                ('FactorAjustePor', models.DecimalField(decimal_places=2, max_digits=30)),
                ('FactorAjuste', models.DecimalField(decimal_places=2, max_digits=30)),
                ('Mop', models.DecimalField(decimal_places=2, max_digits=30)),
                ('MopPor', models.DecimalField(decimal_places=2, max_digits=30)),
                ('TotalTransportista', models.DecimalField(decimal_places=2, max_digits=30)),
                ('ViajeRedondo', models.BooleanField()),
                ('IDUsuarioAlta', models.IntegerField(blank=True, null=True)),
                ('IDUsuarioMod', models.IntegerField(blank=True, null=True)),
                ('FechaAlta', models.DateTimeField(blank=True, null=True)),
                ('FechaModificacion', models.DateTimeField(blank=True, null=True)),
                ('Actividad', models.BooleanField(default=1)),
            ],
            options={
                'db_table': 'Costeo',
            },
        ),
        migrations.CreateModel(
            name='CostosOperativos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Combustible', models.DecimalField(decimal_places=2, max_digits=30)),
                ('Casetas', models.DecimalField(decimal_places=2, max_digits=30)),
                ('Operador', models.DecimalField(decimal_places=2, max_digits=30)),
                ('Subtotal1', models.DecimalField(decimal_places=2, max_digits=30)),
                ('MttoUnidad', models.DecimalField(decimal_places=2, max_digits=30)),
                ('LlantasUnidad', models.DecimalField(decimal_places=2, max_digits=30)),
                ('Gps', models.DecimalField(decimal_places=2, max_digits=30)),
                ('Seguro', models.DecimalField(decimal_places=2, max_digits=30)),
                ('PlacasTenencia', models.DecimalField(decimal_places=2, max_digits=30)),
                ('SubTotal2', models.DecimalField(decimal_places=2, max_digits=30)),
                ('Admvo', models.DecimalField(decimal_places=2, max_digits=30)),
                ('Financieros', models.DecimalField(decimal_places=2, max_digits=30)),
                ('DeprUnidad', models.DecimalField(decimal_places=2, max_digits=30)),
                ('DeprRemolque', models.DecimalField(decimal_places=2, max_digits=30)),
                ('Subtotal3', models.DecimalField(decimal_places=2, max_digits=30)),
                ('IDUsuarioAlta', models.IntegerField(blank=True, null=True)),
                ('IDUsuarioMod', models.IntegerField(blank=True, null=True)),
                ('FechaAlta', models.DateTimeField(blank=True, null=True)),
                ('FechaModificacion', models.DateTimeField(blank=True, null=True)),
                ('Actividad', models.BooleanField(default=1)),
            ],
            options={
                'db_table': 'CostosOperativos',
            },
        ),
        migrations.CreateModel(
            name='Depreciacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Meses', models.IntegerField()),
                ('CostosUnidad', models.DecimalField(decimal_places=2, max_digits=30)),
                ('CostosCaja', models.DecimalField(decimal_places=2, max_digits=30)),
                ('ViajesMes', models.IntegerField()),
                ('KmsMesXunidad', models.DecimalField(decimal_places=2, max_digits=30)),
                ('KmsMaximo', models.DecimalField(decimal_places=2, max_digits=30)),
                ('DepTracto', models.DecimalField(decimal_places=2, max_digits=30)),
                ('DepCaja', models.DecimalField(decimal_places=2, max_digits=30)),
                ('RentaGPS', models.DecimalField(decimal_places=2, max_digits=30)),
                ('PlacasTenencia', models.DecimalField(decimal_places=2, max_digits=30)),
                ('Seguro', models.DecimalField(decimal_places=2, max_digits=30)),
                ('Admvo', models.IntegerField()),
                ('Financieros', models.IntegerField()),
                ('MttoUnidadXkm', models.DecimalField(decimal_places=2, max_digits=30)),
                ('Llantas', models.DecimalField(decimal_places=2, max_digits=30)),
                ('Operador', models.DecimalField(decimal_places=2, max_digits=30)),
                ('IDUsuarioAlta', models.IntegerField(blank=True, null=True)),
                ('IDUsuarioMod', models.IntegerField(blank=True, null=True)),
                ('FechaAlta', models.DateTimeField(blank=True, null=True)),
                ('FechaModificacion', models.DateTimeField(blank=True, null=True)),
                ('Actividad', models.BooleanField(default=1)),
            ],
            options={
                'db_table': 'Depreciacion',
            },
        ),
        migrations.CreateModel(
            name='FactoresPremisas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Unidad', models.IntegerField()),
                ('Caja', models.IntegerField()),
                ('Km', models.DecimalField(decimal_places=2, max_digits=30)),
                ('KmMensuales', models.DecimalField(decimal_places=2, max_digits=30)),
                ('CasetaSingle', models.DecimalField(decimal_places=2, max_digits=30)),
                ('Rendimiento', models.DecimalField(decimal_places=2, max_digits=30)),
                ('Diesel', models.DecimalField(decimal_places=2, max_digits=30)),
                ('DieselSinIva', models.DecimalField(decimal_places=2, max_digits=30)),
                ('IDUsuarioAlta', models.IntegerField(blank=True, null=True)),
                ('IDUsuarioMod', models.IntegerField(blank=True, null=True)),
                ('FechaAlta', models.DateTimeField(blank=True, null=True)),
                ('FechaModificacion', models.DateTimeField(blank=True, null=True)),
                ('Actividad', models.BooleanField(default=1)),
            ],
            options={
                'db_table': 'FactoresPremisas',
            },
        ),
        migrations.AddField(
            model_name='costeo',
            name='IDCostosOperativos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Costeo.CostosOperativos'),
        ),
        migrations.AddField(
            model_name='costeo',
            name='IDDepreciacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Costeo.Depreciacion'),
        ),
        migrations.AddField(
            model_name='costeo',
            name='IDFactoresPremisas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Costeo.FactoresPremisas'),
        ),
        migrations.AddField(
            model_name='costeo',
            name='IDModelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Rutas.Modelos'),
        ),
        migrations.AddField(
            model_name='costeo',
            name='IDRuta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rutas.Rutas'),
        ),
        migrations.AddField(
            model_name='costeo',
            name='IDTipoUnidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Rutas.TiposUnidades'),
        ),
    ]
