# Generated by Django 2.1.12 on 2020-06-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransportistasProspecto', '0002_auto_20200624_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportistasprospectos',
            name='IDTipo',
        ),
        migrations.AddField(
            model_name='transportistasprospectos',
            name='IDTipo',
            field=models.ManyToManyField(related_name='TiposXTransportita', to='TransportistasProspecto.Tipos'),
        ),
    ]
